# -*- coding: utf-8 -*-
"""Prodigy- Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPc3vOJaZNf3jAHtkzFibpwKMA3fChkM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('task.csv')

df.info()

df.isnull().sum()

df.head()

"""#Handling Missing Values"""

df.dropna(inplace=True)

df.isnull().sum()

"""#Aggregations

"""

# Calculate the average of columns from the 5th onwards and store in 'Average' column
df['Average'] = df.iloc[:, 4:].mean(axis=1)
df

top5 = df.sort_values(by='Average', ascending=False).head(5)



top5.head()

top5.isnull().sum()

"""#Visualisation of Categorical and Distribution Variables

"""

plt.figure(figsize=(10, 6))
plt.bar(top5['Country Name'], top5['Average'])
plt.xlabel('Country Name')
plt.ylabel('Average')
plt.title("Top 5 Countries by Average Count")
plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for better visibility
plt.tight_layout() # Adjust layout to prevent labels from getting cut off
plt.show()